# Generated by Django 5.1.7 on 2025-07-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('age_group', models.CharField(choices=[('영유아', '영유아'), ('청소년', '청소년'), ('대학생·청년', '대학생·청년'), ('중장년', '중장년'), ('노인', '노인'), ('전연령', '전연령')], default='전연령', max_length=20)),
                ('like_count', models.IntegerField(default=0)),
                ('scrap_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policylist_likes', to='login.user')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policylist_policy_likes', to='policyList.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('scrap_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyList.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
