# Generated by Django 5.1.7 on 2025-07-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age_group', models.CharField(choices=[('영유아', '영유아'), ('청소년', '청소년'), ('대학생·청년', '대학생·청년'), ('중장년', '중장년'), ('노인', '노인'), ('전연령', '전연령')], default='전연령', max_length=20)),
            ],
        ),
    ]
