# Generated by Django 5.1.7 on 2025-07-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='review',
            name='policy',
        ),
    ]
